version = 1
SPDX-PackageName = "certgine"
SPDX-PackageDownloadLocation = "https://github.com/morihofi/certgine"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023-2025 Moritz Hofmann <info@morihofi.de>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "certgine-web-legacy/src/main/resources/static/**.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "2002-2008 GNOME Foundation"
SPDX-License-Identifier = "GPL-2.0-or-later"
