@param String baseUrl

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>About</title>
    <link rel="stylesheet" type="text/css" href="static/style.css">
</head>
<body>
<div id="wrapper">
    <h1>About</h1>
    <p>This interface allows you to download root certificates.</p>
    <div id="footer">Powered by <a href="https://github.com/morihofi/acmeserver">morihofi's ACME Server</a> | Icons by Gnome Icon Theme 2.18.0</div>
</div>
</body>
</html>
