#!/bin/sh


# Run acme server post-setup wizard
java -jar /opt/acmeserver/acmeserver.jar --postsetup

# Reload systemd manager configuration
systemctl daemon-reload

# Enable and start the ACME Server service
systemctl enable acmeserver
systemctl start acmeserver
