openapi: 3.0.1
info:
  title: Certgine API
  version: 1.0.0
paths:
  /api/core/users/login:
    post:
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                totp:
                  type: string
                webauthnId:
                  type: string
      responses:
        '200':
          description: Login result
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  totpRequired:
                    type: boolean
                  webauthnRequired:
                    type: boolean
  /api/core/users/register:
    post:
      summary: Register user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Success
  /api/core/users/logout:
    post:
      summary: Logout user
      responses:
        '204':
          description: Logged out
  /api/core/status:
    get:
      summary: Status information
      responses:
        '200':
          description: Status JSON
          content:
            application/json:
              schema:
                type: object
                properties:
                  readiness:
                    type: string
                  firstrun:
                    type: boolean
  /api/core/users/info:
    get:
      summary: Information about current user
      responses:
        '200':
          description: User information
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  admin:
                    type: boolean
                  groups:
                    type: array
                    items:
                      type: string
  /api/core/users/sessions:
    get:
      summary: List user sessions
      responses:
        '200':
          description: Sessions list
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    created:
                      type: string
                      format: date-time
                    expires:
                      type: string
                      format: date-time
