<div id="top-menu">
    <table role="presentation" cellpadding="0" cellspacing="0">
        <tr>
            <td>
                <span>
                    <a href="./"><img src="static/go-home.png" alt="Home" width="16" height="16">&nbsp;Home</a>
                </span>
            </td>
            <td>
                <span>
                    <a href="about"><img src="static/info.png" alt="About" width="16" height="16">&nbsp;About</a>
                </span>
            </td>
            <td>
                <span>
                    <a href="help"><img src="static/help.png" alt="Help" width="16" height="16">&nbsp;Help</a>
                </span>
            </td>
        </tr>
    </table>
</div>